### ISSUE TITLE
RGB backbone pre-training

### ISSUE THREAD

**Issue by sjz000** [ShaohuaDong2021/DPLNet#6]
Thank you very much for your work, may I ask which data set is used for pre-training of the RGB backbone in your model?

**Comment by ShaohuaDong2021** [comment]
Hello, we do not pretrain our RGB model. We use the SegFormer-B5 as the RGB backbone, I think they pretrained this model on ImageNet.

**Comment by sjz000** [comment]
Thanks for your reply.
